name: test
on:
  push:
    branches:
    - main
  workflow_dispatch:
  pull_request:
    paths:
    - src/**
    - pyproject.toml
    - tests/**
    - .github/workflows/test.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Hatch
      uses: pypa/hatch@install
    - run: hatch fmt --check && hatch run mypy
  test:
    runs-on: {{ "${{ matrix.os }}" }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python:
        - 3.9
        - '3.10'
        - 3.11
        - 3.12
        - 3.13
    steps:
    - uses: actions/checkout@v4
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: test
      run: hatch test -c -py {{ "${{ matrix.python }}" }}
